### ISSUE TITLE
ipcs: invalid structure member offset: idr_top

### ISSUE THREAD

**Issue by leitao** [crash-utility/crash#23]
Currently if you calls `ipcs` on new kernels, you got:

> crash> ipcs -m
> SHMID_KERNEL     KEY      SHMID      UID   PERMS BYTES      NATTCH STATUS
> 
> ipcs: invalid structure member offset: idr_top
> FILE: ipcs.c  LINE: 628  FUNCTION: idr_find()
> 
> [/usr/bin/crash] error trace: 69b16c28930 => 69b16c282d8 => 69b16bc8e98 => 69b16a91488
> 
> ipcs: invalid structure member offset: idr_top
> FILE: ipcs.c  LINE: 628  FUNCTION: idr_find()
> 
> crash> ipcs -M
> 
> ipcs: invalid structure member offset: idr_top
> FILE: ipcs.c  LINE: 628  FUNCTION: idr_find()
> 
> [/usr/bin/crash] error trace: 69b16c28930 => 69b16c282d8 => 69b16bc8e98 => 69b16a91488
> 
> ipcs: invalid structure member offset: idr_top
> FILE: ipcs.c  LINE: 628  FUNCTION: idr_find()

This was caused after the Linux code decided to implement IDR using a radix tree, which is not how 'crash' is reading it.

>     commit 0a835c4f090af2c76fc2932c539c3b32fd21fbbb
>     Author: Matthew Wilcox <mawilcox@microsoft.com>
>     Date:   Tue Dec 20 10:27:56 2016 -0500
> 
>     Reimplement IDR and IDA using the radix tree
>     
>     The IDR is very similar to the radix tree.  It has some functionality that
>     the radix tree did not have (alloc next free, cyclic allocation, a
>     callback-based for_each, destroy tree), which is readily implementable on
>     top of the radix tree.  A few small changes were needed in order to use a
>     tag to represent nodes with free space below them.  More extensive
>     changes were needed to support storing NULL as a valid entry in an IDR.
>     Plain radix trees still interpret NULL as a not-present entry.
>     
>     The IDA is reimplemented as a client of the newly enhanced radix tree.  As
>     in the current implementation, it uses a bitmap at the last level of the
>     tree.

**Comment by crash-utility** [comment]
Do you have a patch ready to go?

If not, it would be much more helpful to post this kind of information to
the crash-utility@redhat.com mailing list.  There you will have a broad 
audience of a several hundred developers, and possibly somebody that has
interest and the time to look into it. 

It looks like this has been the case since 4.11, but nobody's noticed
until now.

Dave
  

----- Original Message -----

**Comment by leitao** [comment]
Hi Dave, 

I do not have the patch, I just wanted to report this bug when using crash with new kernel. I will send an email to the mailing list then.

Thanks

**Comment by crash-utility** [comment]
Hi Breno,

As it turns out, the manner in which Fujitsu implemented the ipcs crash command made it fairly
easy to plug in the use of the updated radix tree based IDR facility. And while doing so, I found 
a bug that would cause certain IPCS entries to be rejected because of a faulty read of the
embedded "kern_ipc_perm.deleted" member.  

Thanks for the report!
