### ISSUE TITLE
Failing to evaluate - You can't do that without a process to debug

### ISSUE THREAD

**Issue by nhed** [crash-utility/crash#30]
As I am able to evaluate two values (casting pointers to `uint`s) - I should be able to figure out the distance between said pointers (note - don't want pointer math)

As can be seen I can evaluate each cated-pointer as can be seen in `$39` & `$40`
but when i try to evaluate/print the byte-delta between those `crash` reports an error from `gdb`, but if I force it into `gdb`  as can be seen in the last line it just works.  So looks like something in the `crash` command-line processing is eating up the `-` (minus)

```
crash> p ((uint)((struct sk_buff*)0xe47d9900)->tail)
$39 = 3778076956
crash> p ((uint)((struct sk_buff*)0xe47d9900)->data)
$40 = 3778076872
crash> p (((uint)((struct sk_buff*)0xe47d9900)->tail) - ((uint)((struct sk_buff*)0xe47d9900)->data))
You can't do that without a process to debug.
p: gdb request failed: p (((uint)((struct sk_buff*)0xe47d9900)->tail) ((uint)((struct sk_buff*)0xe47d9900)->data))
crash> gdb p (((uint)((struct sk_buff*)0xe47d9900)->tail) - ((uint)((struct sk_buff*)0xe47d9900)->data))
$41 = 84
```

**Comment by crash-utility** [comment]
----- Original Message -----
> As I am able to evaluate two values (casting pointers to `uint`s) - I should
> be able to figure out the distance between said pointers (note - don't want
> pointer math)
> 
> As can be seen I can evaluate each cated-pointer as can be seen in `$39` & `$40`
> but when i try to evaluate/print the byte-delta between those `crash` reports
> an error from ``gdb`, but if i force it into `gdb`  as can be seen in the
> last line it just works.  So looks like something in the `crash`
> command-line processing is eating up the `-` (minus)
> 
> 
> ```
> crash> p ((uint)((struct sk_buff*)0xe47d9900)->tail)
> $39 = 3778076956
> crash> p ((uint)((struct sk_buff*)0xe47d9900)->data)
> $40 = 3778076872
> crash> p (((uint)((struct sk_buff*)0xe47d9900)->tail) - ((uint)((struct sk_buff*)0xe47d9900)->data))
> You can't do that without a process to debug.
> p: gdb request failed: p (((uint)((struct sk_buff*)0xe47d9900)->tail) ((uint)((struct sk_buff*)0xe47d9900)->data))
> crash> gdb p (((uint)((struct sk_buff*)0xe47d9900)->tail) - ((uint)((struct sk_buff*)0xe47d9900)->data))
> $41 = 84
> ```


Yeah, the call from cmp_p() to concat_args() is purposefully extracting it.

  /*
   *  Concatenates the tokens in the global args[] array into one string,
   *  separating each token with one space.  If the no_options flag is set,
   *  don't include any args beginning with a dash character.
   */
  char *
  concat_args(char *buf, int arg, int no_options)
  {
          int i;
  
          BZERO(buf, BUFSIZE);
  
          for (i = arg; i < argcnt; i++) {
                  if (no_options && STRNEQ(args[i], "-"))
                          continue;
                  strcat(buf, args[i]);
                  strcat(buf, " ");
          }
  
          return(strip_ending_whitespace(buf));
  }

If this debug patch is added you can see it:

  --- tools.c	2018-11-16 14:39:48.962081275 -0500
  +++ tools.c	2019-01-24 11:50:26.408509742 -0500
  @@ -1567,12 +1567,13 @@ concat_args(char *buf, int arg, int no_o
   	BZERO(buf, BUFSIZE);
   
           for (i = arg; i < argcnt; i++) {
  +fprintf(fp, "args[%d]: [%s]\n", i, args[i]);
   		if (no_options && STRNEQ(args[i], "-"))
   			continue;
                   strcat(buf, args[i]);
                   strcat(buf, " ");
           }
  -
  +fprintf(fp, "concat_args: [%s]\n", buf);
   	return(strip_ending_whitespace(buf));
   }
  
Normally expressions encompassed by parentheses get passed as single argument:

  crash> p (3 - 1)
  args[0]: [p]
  args[1]: [(3 - 1)]
  concat_args: [p (3 - 1) ]
  $3 = 2
  crash>

But in this case, it's being broken up:

  crash> p (((uint)((struct sk_buff*)0xffff880311e08000)->tail) - ((uint)((struct sk_buff*)0xffff880311e08000)->data))
  args[0]: [p]
  args[1]: [(((uint)((struct]
  args[2]: [sk_buff*)0xffff880311e08000)->tail)]
  args[3]: [-]
  args[4]: [((uint)((struct]
  args[5]: [sk_buff*)0xffff880311e08000)->data))]
  concat_args: [p (((uint)((struct sk_buff*)0xffff880311e08000)->tail) ((uint)((struct sk_buff*)0xffff880311e08000)->data)) ]
  You can't do that without a process to debug.
  p: gdb request failed: p (((uint)((struct sk_buff*)0xffff880311e08000)->tail) ((uint)((struct sk_buff*)0xffff880311e08000)->data))
  crash> 
 
So it goes back to the original call from process_command_line()
to parse_line(), which is getting confused by the multiple parentheses 
in the expression.  The "expression" variable in parse_line() should 
probably be a counter instead of a boolean or something like that,
but I'm hesitant to screw around with it since it's such a commonly-called
function.

Better to use "gdb" as you have, or "p ($39 - $40)".

Dave

**Comment by crash-utility** [comment]
----- Original Message -----

...

> On the other hand, I don't recall why cmd_p() is setting the "no_options" flag
> to TRUE?  There must have been a reason, but I don't recall why.  Hmmm...

No, I don't believe there ever was a reason.  Just removed it:

  https://github.com/crash-utility/crash/commit/977c3a20a053eaff5b1f0c95246f88cd66712f27

  Fix for the "p" command if the expression contains more than one
  opening parenthesis character and a minus/dash sign.  Without the
  patch, the minus/dash sign will get dropped from the command prior
  to it being passed on to gdb for evaluation, and the command will
  fail with the message "p: gdb request failed: <expression>",
  where the <expression> string will not contain the minus/dash sign.
  (anderson@redhat.com)

Thanks,
  Dave

**Comment by nhed** [comment]
Works! thanks Dave
