### ISSUE TITLE
New tag cycle/cadence

### ISSUE THREAD

**Issue by guilhermepiccoli** [crash-utility/crash#48]
Hi Dave, I'd like to ask you about the cadence of tagging in the project.

What triggers this question is that we wanna bump Ubuntu's version, and for that we'd like to bump Debian version first (the process works this way). But I've checked the upstream (which I believe corresponds to this repo), and we are at 7.2.7 for 4 months with about ~30 commits on top of it.

Given the repo history, you seem to be bumping versions within a 4-month cycle - if that's true and a bump to 7.2.8 comes soon, I'd prefer to wait for it and ask debian to bump to 7.2.8 directly.

Thanks in advance!

**Comment by crash-utility** [comment]
----- Original Message -----
> Hi Dave, I'd like to ask you about the cadence of tagging in the project.
> 
> What triggers this question is that we wanna bump Ubuntu's version, and for
> that we'd like to bump Debian version first (the process works this way).
> But I've checked the upstream (which I believe corresponds to this repo),
> and we are at 7.2.7 for 4 months with about ~30 commits on top of it.
> 
> Given the repo history, you seem to be bumping versions within a 4-month
> cycle - if that's true and a bump to 7.2.8 comes soon, I'd prefer to wait
> for it and ask debian to bump to 7.2.8 directly.
> 
> Thanks in advance!
> 
> --

I have been waiting for:

 (1) Linux 5.5 to be released upstream,
 (2) for it to then be built into a Red Hat kernel package in-house, and
 (3) for the latest crash sources to be verified against that kernel.  

Since the kernel was released upstream just today, I do expect to be doing a 
crash release shortly.  However, step (2) is out of my control, and sometimes
it takes several days.

Dave

**Comment by guilhermepiccoli** [comment]
Thanks a lot for your prompt response Dave. I'll wait your release since it's expected soon - this way, we can have a recent upstream version in Debian and Ubuntu!
Cheers,


Guilherme

**Comment by guilhermepiccoli** [comment]
Thanks Dave, new tag 7.2.8 is up! Will close this one =)
