### ISSUE TITLE
crash 7.2.5 cannot make success under Debian 9 (kernel 4.14.151)

### ISSUE THREAD

**Issue by czn92** [crash-utility/crash#53]
I try:
tar -xf crash-7.2.5.tar.gz --> cd crash-7.2.5 --> make
to make a crash tool to analyze my vmcore. But it fails with the following error msg at the end:

```
make  all-recursive
make[10]: Nothing to be done for 'all-am'.
make[3]: Nothing to be done for 'all-target'.

crash build failed

Makefile:229: recipe for target 'gdb_merge' failed
make[1]: *** [gdb_merge] Error 1
Makefile:224: recipe for target 'all' failed
make: *** [all] Error 2
```
How does this issue occurs? Because there is no more any other error during compiling. 
By the way, because my gcc version is larger than 4.1, I add "--disable-werror" when building gdb config to avoid the error shown below:

```
bfd.h:537:65: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define bfd_set_cacheable(abfd,bool) (((abfd)->cacheable = bool), TRUE)
                                                                 ^
opncls.c:234:5: note: in expansion of macro 'bfd_set_cacheable'
     bfd_set_cacheable (nbfd, TRUE);
     ^
```

**Comment by crash-utility** [comment]
----- Original Message -----
> I try:
> tar -xf crash-7.2.5.tar.gz --> cd crash-7.2.5 --> make
> to make a crash tool to analyze my vmcore. But it fails with the following
> error msg at the end:
> 
> ```
> make  all-recursive
> make[10]: Nothing to be done for 'all-am'.
> make[3]: Nothing to be done for 'all-target'.
> 
> crash build failed
> 
> Makefile:229: recipe for target 'gdb_merge' failed
> make[1]: *** [gdb_merge] Error 1
> Makefile:224: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> How does this issue occurs? Because there is no more any other error during compiling.

I have no idea without seeing the full build.log.

> By the way, because my gcc version is larger than 4.1, I add
> "--disable-werror" when building gdb config to avoid the error shown below:
> 
> ```
> bfd.h:537:65: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
>  #define bfd_set_cacheable(abfd,bool) (((abfd)->cacheable = bool), TRUE)
>                                                                  ^
> opncls.c:234:5: note: in expansion of macro 'bfd_set_cacheable'
>      bfd_set_cacheable (nbfd, TRUE);
>      ^
> ```

The bfd library build has been built without -Werror since crash-7.1.8,
so I don't know how that can happen:

$ git show c27dabf7f9f020aaede71eb7bd3b872f0098bb9e
commit c27dabf7f9f020aaede71eb7bd3b872f0098bb9e
Author: Dave Anderson <anderson@redhat.com>
Date:   Tue Feb 21 11:17:13 2017 -0500

    Removed -Werror from the bfd and opcode library builds.
    (anderson@redhat.com)

diff --git a/gdb-7.6.patch b/gdb-7.6.patch
index eb0029d..094f01a 100644
--- a/gdb-7.6.patch
+++ b/gdb-7.6.patch
@@ -2299,3 +2299,27 @@ diff -up gdb-7.6/bfd/elf64-ppc.c.orig gdb-7.6/bfd/elf64-ppc.c
  
          do_cleanups (old_chain);
  }
+diff -up gdb-7.6/bfd/configure.orig gdb-7.6/bfd/configure
+--- gdb-7.6/bfd/configure.orig 2017-02-17 17:19:51.654898822 -0500
++++ gdb-7.6/bfd/configure      2017-02-17 17:19:57.922038757 -0500
+@@ -12193,7 +12193,7 @@ fi
+ 
+ NO_WERROR=
+ if test "${ERROR_ON_WARNING}" = yes ; then
+-    GCC_WARN_CFLAGS="$GCC_WARN_CFLAGS -Werror"
++    GCC_WARN_CFLAGS="$GCC_WARN_CFLAGS"
+     NO_WERROR="-Wno-error"
+ fi
+ 
+diff -up gdb-7.6/opcodes/configure.orig gdb-7.6/opcodes/configure
+--- gdb-7.6/opcodes/configure.orig     2017-02-17 17:19:08.849943016 -0500
++++ gdb-7.6/opcodes/configure  2017-02-17 17:19:23.256264699 -0500
+@@ -11539,7 +11539,7 @@ fi
+ 
+ NO_WERROR=
+ if test "${ERROR_ON_WARNING}" = yes ; then
+-    GCC_WARN_CFLAGS="$GCC_WARN_CFLAGS -Werror"
++    GCC_WARN_CFLAGS="$GCC_WARN_CFLAGS"
+     NO_WERROR="-Wno-error"
+ fi
+ 
$ git describe --contains c27dabf7f9f020aaede71eb7bd3b872f0098bb9e
7.1.8~1
$ 

What happens with a current version?

**Comment by czn92** [comment]
> ----- Original Message -----
>  I try:
>  tar -xf crash-7.2.5.tar.gz --> cd crash-7.2.5 --> make
>  to make a crash tool to analyze my vmcore. But it fails with the following
>  error msg at the end:
> 
>  ```
>  make  all-recursive
>  make[10]: Nothing to be done for 'all-am'.
>  make[3]: Nothing to be done for 'all-target'.
> 
>  crash build failed
> 
>  Makefile:229: recipe for target 'gdb_merge' failed
>  make[1]: *** [gdb_merge] Error 1
>  Makefile:224: recipe for target 'all' failed
>  make: *** [all] Error 2
>  ```
>  How does this issue occurs? Because there is no more any other error during compiling.
> I have no idea without seeing the full build.log.
>  By the way, because my gcc version is larger than 4.1, I add
>  "--disable-werror" when building gdb config to avoid the error shown below:
> 
>  ```
>  bfd.h:537:65: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
>   #define bfd_set_cacheable(abfd,bool) (((abfd)->cacheable = bool), TRUE)
>                                                                   ^
>  opncls.c:234:5: note: in expansion of macro 'bfd_set_cacheable'
>       bfd_set_cacheable (nbfd, TRUE);
>       ^
>  ```
> The bfd library build has been built without -Werror since crash-7.1.8,
> so I don't know how that can happen:
> 
> $ git show c27dabf
> commit c27dabf
> Author: Dave Anderson <anderson@redhat.com>
> Date:   Tue Feb 21 11:17:13 2017 -0500
> 
>     Removed -Werror from the bfd and opcode library builds.
>     (anderson@redhat.com)
> 
> diff --git a/gdb-7.6.patch b/gdb-7.6.patch
> index eb0029d..094f01a 100644
> --- a/gdb-7.6.patch
> +++ b/gdb-7.6.patch
> @@ -2299,3 +2299,27 @@ diff -up gdb-7.6/bfd/elf64-ppc.c.orig gdb-7.6/bfd/elf64-ppc.c
> 
>           do_cleanups (old_chain);
>   }
> +diff -up gdb-7.6/bfd/configure.orig gdb-7.6/bfd/configure
> +--- gdb-7.6/bfd/configure.orig 2017-02-17 17:19:51.654898822 -0500
> ++++ gdb-7.6/bfd/configure      2017-02-17 17:19:57.922038757 -0500
> +@@ -12193,7 +12193,7 @@ fi
> +
> + NO_WERROR=
> + if test "${ERROR_ON_WARNING}" = yes ; then
> +-    GCC_WARN_CFLAGS="$GCC_WARN_CFLAGS -Werror"
> ++    GCC_WARN_CFLAGS="$GCC_WARN_CFLAGS"
> +     NO_WERROR="-Wno-error"
> + fi
> +
> +diff -up gdb-7.6/opcodes/configure.orig gdb-7.6/opcodes/configure
> +--- gdb-7.6/opcodes/configure.orig     2017-02-17 17:19:08.849943016 -0500
> ++++ gdb-7.6/opcodes/configure  2017-02-17 17:19:23.256264699 -0500
> +@@ -11539,7 +11539,7 @@ fi
> +
> + NO_WERROR=
> + if test "${ERROR_ON_WARNING}" = yes ; then
> +-    GCC_WARN_CFLAGS="$GCC_WARN_CFLAGS -Werror"
> ++    GCC_WARN_CFLAGS="$GCC_WARN_CFLAGS"
> +     NO_WERROR="-Wno-error"
> + fi
> +
> $ git describe --contains c27dabf
> 7.1.8~1
> $
> 
> What happens with a current version?

Thanks for the reply.
I've found my mistakes, and it worked just fine when compiling crash. You can just delete this issue.

**Comment by k-hagio** [comment]
OK, good, thanks for letting us know.  Closing.
